[2025-10-17T20:36:26.385+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_pipeline.dbt_run scheduled__2025-10-16T00:00:00+00:00 [queued]>
[2025-10-17T20:36:26.394+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_pipeline.dbt_run scheduled__2025-10-16T00:00:00+00:00 [queued]>
[2025-10-17T20:36:26.394+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-10-17T20:36:26.406+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): dbt_run> on 2025-10-16 00:00:00+00:00
[2025-10-17T20:36:26.411+0000] {standard_task_runner.py:57} INFO - Started process 216 to run task
[2025-10-17T20:36:26.414+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dbt_run_pipeline', 'dbt_run', 'scheduled__2025-10-16T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpcsqzhi4_']
[2025-10-17T20:36:26.417+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask dbt_run
[2025-10-17T20:36:26.435+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-17T20:36:26.476+0000] {task_command.py:415} INFO - Running <TaskInstance: dbt_run_pipeline.dbt_run scheduled__2025-10-16T00:00:00+00:00 [running]> on host 00b52ae6051a
[2025-10-17T20:36:26.557+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_run_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-10-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-16T00:00:00+00:00'
[2025-10-17T20:36:26.558+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-17T20:36:26.559+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/dbt_project && dbt run --profiles-dir .']
[2025-10-17T20:36:26.568+0000] {subprocess.py:86} INFO - Output:
[2025-10-17T20:36:26.571+0000] {subprocess.py:93} INFO - /bin/bash: line 1: cd: /opt/***/dbt_project: No such file or directory
[2025-10-17T20:36:26.571+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-17T20:36:26.582+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-17T20:36:26.585+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=dbt_run_pipeline, task_id=dbt_run, execution_date=20251016T000000, start_date=20251017T203626, end_date=20251017T203626
[2025-10-17T20:36:26.597+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 6 for task dbt_run (Bash command failed. The command returned a non-zero exit code 1.; 216)
[2025-10-17T20:36:26.635+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-10-17T20:36:26.662+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-17T21:03:50.209+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_pipeline.dbt_run scheduled__2025-10-16T00:00:00+00:00 [queued]>
[2025-10-17T21:03:50.221+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_pipeline.dbt_run scheduled__2025-10-16T00:00:00+00:00 [queued]>
[2025-10-17T21:03:50.221+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-10-17T21:03:50.236+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): dbt_run> on 2025-10-16 00:00:00+00:00
[2025-10-17T21:03:50.240+0000] {standard_task_runner.py:57} INFO - Started process 211 to run task
[2025-10-17T21:03:50.245+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dbt_run_pipeline', 'dbt_run', 'scheduled__2025-10-16T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmp_yyouy_d']
[2025-10-17T21:03:50.249+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask dbt_run
[2025-10-17T21:03:50.271+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-17T21:03:50.335+0000] {task_command.py:415} INFO - Running <TaskInstance: dbt_run_pipeline.dbt_run scheduled__2025-10-16T00:00:00+00:00 [running]> on host b0360591ae5e
[2025-10-17T21:03:50.463+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_run_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-10-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-16T00:00:00+00:00'
[2025-10-17T21:03:50.466+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-17T21:03:50.468+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/dbt && dbt run --profiles-dir /opt/***/dbt']
[2025-10-17T21:03:50.483+0000] {subprocess.py:86} INFO - Output:
[2025-10-17T21:03:53.662+0000] {subprocess.py:93} INFO - [0m21:03:53  Running with dbt=1.7.0
[2025-10-17T21:03:53.994+0000] {subprocess.py:93} INFO - [0m21:03:53  Registered adapter: postgres=1.7.0
[2025-10-17T21:03:54.066+0000] {subprocess.py:93} INFO - [0m21:03:54  Found 1 model, 1 seed, 0 sources, 0 exposures, 0 metrics, 401 macros, 0 groups, 0 semantic models
[2025-10-17T21:03:54.069+0000] {subprocess.py:93} INFO - [0m21:03:54
[2025-10-17T21:03:54.171+0000] {subprocess.py:93} INFO - [0m21:03:54  Concurrency: 1 threads (target='dev')
[2025-10-17T21:03:54.172+0000] {subprocess.py:93} INFO - [0m21:03:54
[2025-10-17T21:03:54.180+0000] {subprocess.py:93} INFO - [0m21:03:54  1 of 1 START sql table model public_public.transform_data ...................... [RUN]
[2025-10-17T21:03:54.309+0000] {subprocess.py:93} INFO - [0m21:03:54  1 of 1 OK created sql table model public_public.transform_data ................. [[32mSELECT 3[0m in 0.13s]
[2025-10-17T21:03:54.325+0000] {subprocess.py:93} INFO - [0m21:03:54
[2025-10-17T21:03:54.326+0000] {subprocess.py:93} INFO - [0m21:03:54  Finished running 1 table model in 0 hours 0 minutes and 0.25 seconds (0.25s).
[2025-10-17T21:03:54.341+0000] {subprocess.py:93} INFO - [0m21:03:54
[2025-10-17T21:03:54.342+0000] {subprocess.py:93} INFO - [0m21:03:54  [32mCompleted successfully[0m
[2025-10-17T21:03:54.342+0000] {subprocess.py:93} INFO - [0m21:03:54
[2025-10-17T21:03:54.343+0000] {subprocess.py:93} INFO - [0m21:03:54  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-10-17T21:03:55.204+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-10-17T21:03:55.240+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=dbt_run_pipeline, task_id=dbt_run, execution_date=20251016T000000, start_date=20251017T210350, end_date=20251017T210355
[2025-10-17T21:03:55.267+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-10-17T21:03:55.290+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-17T21:04:47.423+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_pipeline.dbt_run scheduled__2025-10-16T00:00:00+00:00 [queued]>
[2025-10-17T21:04:47.431+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_pipeline.dbt_run scheduled__2025-10-16T00:00:00+00:00 [queued]>
[2025-10-17T21:04:47.431+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-10-17T21:04:47.442+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): dbt_run> on 2025-10-16 00:00:00+00:00
[2025-10-17T21:04:47.447+0000] {standard_task_runner.py:57} INFO - Started process 270 to run task
[2025-10-17T21:04:47.450+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dbt_run_pipeline', 'dbt_run', 'scheduled__2025-10-16T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpk38nk9t7']
[2025-10-17T21:04:47.453+0000] {standard_task_runner.py:85} INFO - Job 24: Subtask dbt_run
[2025-10-17T21:04:47.469+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-17T21:04:47.506+0000] {task_command.py:415} INFO - Running <TaskInstance: dbt_run_pipeline.dbt_run scheduled__2025-10-16T00:00:00+00:00 [running]> on host b0360591ae5e
[2025-10-17T21:04:47.577+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_run_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-10-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-16T00:00:00+00:00'
[2025-10-17T21:04:47.578+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-17T21:04:47.579+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/dbt && dbt run --profiles-dir /opt/***/dbt']
[2025-10-17T21:04:47.587+0000] {subprocess.py:86} INFO - Output:
[2025-10-17T21:04:50.617+0000] {subprocess.py:93} INFO - [0m21:04:50  Running with dbt=1.7.0
[2025-10-17T21:04:50.971+0000] {subprocess.py:93} INFO - [0m21:04:50  Registered adapter: postgres=1.7.0
[2025-10-17T21:04:51.050+0000] {subprocess.py:93} INFO - [0m21:04:51  Found 1 model, 1 seed, 0 sources, 0 exposures, 0 metrics, 401 macros, 0 groups, 0 semantic models
[2025-10-17T21:04:51.053+0000] {subprocess.py:93} INFO - [0m21:04:51
[2025-10-17T21:04:51.172+0000] {subprocess.py:93} INFO - [0m21:04:51  Concurrency: 1 threads (target='dev')
[2025-10-17T21:04:51.173+0000] {subprocess.py:93} INFO - [0m21:04:51
[2025-10-17T21:04:51.183+0000] {subprocess.py:93} INFO - [0m21:04:51  1 of 1 START sql table model public_public.transform_data ...................... [RUN]
[2025-10-17T21:04:51.323+0000] {subprocess.py:93} INFO - [0m21:04:51  1 of 1 OK created sql table model public_public.transform_data ................. [[32mSELECT 3[0m in 0.14s]
[2025-10-17T21:04:51.338+0000] {subprocess.py:93} INFO - [0m21:04:51
[2025-10-17T21:04:51.339+0000] {subprocess.py:93} INFO - [0m21:04:51  Finished running 1 table model in 0 hours 0 minutes and 0.28 seconds (0.28s).
[2025-10-17T21:04:51.351+0000] {subprocess.py:93} INFO - [0m21:04:51
[2025-10-17T21:04:51.352+0000] {subprocess.py:93} INFO - [0m21:04:51  [32mCompleted successfully[0m
[2025-10-17T21:04:51.353+0000] {subprocess.py:93} INFO - [0m21:04:51
[2025-10-17T21:04:51.354+0000] {subprocess.py:93} INFO - [0m21:04:51  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-10-17T21:04:52.265+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-10-17T21:04:52.293+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=dbt_run_pipeline, task_id=dbt_run, execution_date=20251016T000000, start_date=20251017T210447, end_date=20251017T210452
[2025-10-17T21:04:52.345+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-10-17T21:04:52.369+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-17T21:17:36.245+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_pipeline.dbt_run scheduled__2025-10-16T00:00:00+00:00 [queued]>
[2025-10-17T21:17:36.253+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_pipeline.dbt_run scheduled__2025-10-16T00:00:00+00:00 [queued]>
[2025-10-17T21:17:36.254+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-10-17T21:17:36.266+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): dbt_run> on 2025-10-16 00:00:00+00:00
[2025-10-17T21:17:36.270+0000] {standard_task_runner.py:57} INFO - Started process 239 to run task
[2025-10-17T21:17:36.274+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dbt_run_pipeline', 'dbt_run', 'scheduled__2025-10-16T00:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmp9oqk37cr']
[2025-10-17T21:17:36.277+0000] {standard_task_runner.py:85} INFO - Job 34: Subtask dbt_run
[2025-10-17T21:17:36.294+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-17T21:17:36.338+0000] {task_command.py:415} INFO - Running <TaskInstance: dbt_run_pipeline.dbt_run scheduled__2025-10-16T00:00:00+00:00 [running]> on host 10529ec04042
[2025-10-17T21:17:36.416+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_run_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-10-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-16T00:00:00+00:00'
[2025-10-17T21:17:36.417+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-17T21:17:36.418+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/dbt && dbt run --profiles-dir /opt/***/dbt']
[2025-10-17T21:17:36.427+0000] {subprocess.py:86} INFO - Output:
[2025-10-17T21:17:39.057+0000] {subprocess.py:93} INFO - [0m21:17:39  Running with dbt=1.7.0
[2025-10-17T21:17:39.380+0000] {subprocess.py:93} INFO - [0m21:17:39  Registered adapter: postgres=1.7.0
[2025-10-17T21:17:39.442+0000] {subprocess.py:93} INFO - [0m21:17:39  Found 1 model, 1 seed, 0 sources, 0 exposures, 0 metrics, 401 macros, 0 groups, 0 semantic models
[2025-10-17T21:17:39.446+0000] {subprocess.py:93} INFO - [0m21:17:39
[2025-10-17T21:17:39.544+0000] {subprocess.py:93} INFO - [0m21:17:39  Concurrency: 1 threads (target='dev')
[2025-10-17T21:17:39.545+0000] {subprocess.py:93} INFO - [0m21:17:39
[2025-10-17T21:17:39.553+0000] {subprocess.py:93} INFO - [0m21:17:39  1 of 1 START sql table model public_public.transform_data ...................... [RUN]
[2025-10-17T21:17:39.695+0000] {subprocess.py:93} INFO - [0m21:17:39  1 of 1 OK created sql table model public_public.transform_data ................. [[32mSELECT 3[0m in 0.14s]
[2025-10-17T21:17:39.723+0000] {subprocess.py:93} INFO - [0m21:17:39
[2025-10-17T21:17:39.724+0000] {subprocess.py:93} INFO - [0m21:17:39  Finished running 1 table model in 0 hours 0 minutes and 0.28 seconds (0.28s).
[2025-10-17T21:17:39.751+0000] {subprocess.py:93} INFO - [0m21:17:39
[2025-10-17T21:17:39.753+0000] {subprocess.py:93} INFO - [0m21:17:39  [32mCompleted successfully[0m
[2025-10-17T21:17:39.754+0000] {subprocess.py:93} INFO - [0m21:17:39
[2025-10-17T21:17:39.756+0000] {subprocess.py:93} INFO - [0m21:17:39  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-10-17T21:17:40.626+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-10-17T21:17:40.654+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=dbt_run_pipeline, task_id=dbt_run, execution_date=20251016T000000, start_date=20251017T211736, end_date=20251017T211740
[2025-10-17T21:17:40.680+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-10-17T21:17:40.705+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
